### ISSUE TITLE
Hash Sum mismatch upon container initialization 

### ISSUE THREAD

**Issue by umkl** [cenk1cenk2/docker-node-fnm#403]
Hey, I am trying to run the docker image using the following docker compose configuration: 

```
version: '3'
services:
  nx:
    image: cenk1cenk2/node-fnm:latest
    environment:
      NODE_APP_INSTANCE: develop
      PACKAGE_MANAGER: npm
      DEFAULTS_COMMAND: npm run start
      SERVICE_0_CWD: .
      PROXY_WORKSPACE_ONLY: 'true'
      FORCE_COLOR: '1'
      BEFORE_ALL: |
        [
          "apt-get update",
          "apt-get install -y protobuf-compiler"
        ]
    ports:
      - 3000-3020:3000-3020
      - 50000:50000
      - 9229-9239:9229-9239
    volumes:
      - .:/data:delegated
      ```

when I want to run the container I get the following error:

```
nx-1  | [I] [before-all] Last modification reported: Wed, 06 May 2020 14:59:20 +0000
nx-1  | [I] [before-all] Get:17 http://deb.debian.org/debian bullseye/main arm64 libc-devtools arm64 2.31-13+deb11u11 [245 kB]
nx-1  | [I] [before-all] Get:18 http://deb.debian.org/debian-security bullseye-security/main arm64 linux-libc-dev arm64 5.10.226-1 [1750 kB]
nx-1  | [I] [before-all] Get:19 http://deb.debian.org/debian bullseye/main arm64 libcrypt-dev arm64 1:4.4.18-4 [108 kB]
nx-1  | [I] [before-all] Get:20 http://deb.debian.org/debian bullseye/main arm64 libtirpc-dev arm64 1.3.1-1+deb11u1 [193 kB]
nx-1  | [I] [before-all] Get:21 http://deb.debian.org/debian bullseye/main arm64 libnsl-dev arm64 1.3.0-2 [66.1 kB]
nx-1  | [I] [before-all] Get:22 http://deb.debian.org/debian bullseye/main arm64 libc6-dev arm64 2.31-13+deb11u11 [2030 kB]
nx-1  | [I] [before-all] Get:23 http://deb.debian.org/debian bullseye/main arm64 zlib1g-dev arm64 1:1.2.11.dfsg-2+deb11u2 [189 kB]
nx-1  | [I] [before-all] Get:24 http://deb.debian.org/debian bullseye/main arm64 libprotobuf23 arm64 3.12.4-1+deb11u1 [781 kB]
nx-1  | [I] [before-all] Get:25 http://deb.debian.org/debian bullseye/main arm64 libprotobuf-lite23 arm64 3.12.4-1+deb11u1 [218 kB]
nx-1  | [I] [before-all] Get:26 http://deb.debian.org/debian bullseye/main arm64 libprotobuf-dev arm64 3.12.4-1+deb11u1 [1164 kB]
nx-1  | [I] [before-all] Get:27 http://deb.debian.org/debian bullseye/main arm64 libprotoc23 arm64 3.12.4-1+deb11u1 [703 kB]
nx-1  | [I] [before-all] Get:28 http://deb.debian.org/debian bullseye/main arm64 manpages-dev all 5.10-1 [2309 kB]
nx-1  | [I] [before-all] Get:29 http://deb.debian.org/debian bullseye/main arm64 protobuf-compiler arm64 3.12.4-1+deb11u1 [75.0 kB]
nx-1  | [I] [before-all] Fetched 14.9 MB in 31s (476 kB/s)
nx-1  | [W] [before-all] E: Failed to fetch http://deb.debian.org/debian/pool/main/libg/libgd2/libgd3_2.3.0-2_arm64.deb  Hash Sum mismatch
nx-1  | [W] [before-all] Hashes of expected file:
nx-1  | [W] [before-all] - SHA256:1e6d6af0c90fe62193b3e51e45f69d075b86d7bde3fb4fd30b60da763aeca43f
nx-1  | [W] [before-all] - MD5Sum:b60061c074b4cce80c243cbc9c168499 [weak]
nx-1  | [W] [before-all] - Filesize:126904 [weak]
nx-1  | [W] [before-all] Hashes of received file:
nx-1  | [W] [before-all] - SHA256:7df88c771cc29646fb0b1160061c393173df6d8a3f5f571d00400dd6dc0ec814
nx-1  | [W] [before-all] - MD5Sum:0bc480a96a607b021478ed201a1ac85f [weak]
nx-1  | [W] [before-all] - Filesize:126904 [weak]
nx-1  | [W] [before-all] Last modification reported: Wed, 06 May 2020 14:59:20 +0000
nx-1  | [W] [before-all] E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
nx-1  | [E] [before-all] [FAIL] $ /usr/bin/env bash > exit status 100
nx-1  | [E] [before-all] exit status 100
nx-1  | [E] [before-all] exit status 100
nx-1  | [F] [before-all] exit status 100
nx-1  | [F] [before-all] exit status 100
nx-1  | [E] [before-all] exit status 100
nx-1 exited with code 1
```

Any help much appreciated
